CREATE TABLE EMPLAYEE (
       RECORD_ID NUMBER,
       FULL_NAME VARCHAR2(255),
       AGE VARCHAR2(255),
       ROLE_ID NUMBER,
       DPT_ID NUMBER,
       ENTRY_DATE DATE
) TABLESPACE FINANCE;

ALTER TABLE EMPLAYEE
ADD CONSTRAINT PK_EMPLAYEE PRIMARY KEY(RECORD_ID);

CREATE SEQUENCE S_EMPLAYEE
INCREMENT BY 1
START WITH 1;